- name: Deploy S3-Lambda-SNS Email Automation
  hosts: localhost
  gather_facts: false

  vars_files:
    - environments/vars.yml

  tasks:

    # ------------------------
    # S3
    # ------------------------
    - name: Ensure S3 bucket exists
      ansible.builtin.shell: |
        aws s3api head-bucket --bucket {{ s3_bucket_name }} >/dev/null 2>&1
        if [ $? -ne 0 ]; then
          aws s3api create-bucket \
            --bucket {{ s3_bucket_name }} \
            --region {{ region }}{% if region != 'us-east-1' %} \
            --create-bucket-configuration LocationConstraint={{ region }}{% endif %}
          echo "created"
        else
          echo "exists"
        fi
      args:
        executable: /bin/bash
        warn: false
      register: s3_bucket_result
      changed_when: "'created' in s3_bucket_result.stdout"

    # ------------------------
    # IAM
    # ------------------------
    - name: Ensure Lambda IAM role exists
      ansible.builtin.shell: |
        aws iam get-role --role-name {{ lambda_role_name }} >/dev/null 2>&1
        if [ $? -ne 0 ]; then
          aws iam create-role \
            --role-name {{ lambda_role_name }} \
            --assume-role-policy-document '{
              "Version":"2012-10-17",
              "Statement":[{
                "Effect":"Allow",
                "Principal":{"Service":"lambda.amazonaws.com"},
                "Action":"sts:AssumeRole"
              }]
            }'
          echo "created"
        else
          echo "exists"
        fi
      args:
        executable: /bin/bash
        warn: false
      register: iam_role_result
      changed_when: "'created' in iam_role_result.stdout"

    - name: Ensure Lambda basic execution policy attached
      ansible.builtin.shell: |
        aws iam list-attached-role-policies --role-name {{ lambda_role_name }} \
          --query "AttachedPolicies[].PolicyArn" \
          --output text | tr '\t' '\n'
      args:
        executable: /bin/bash
        warn: false
      register: attached_policies
      changed_when: false

    - name: Attach Lambda execution policy if missing
      ansible.builtin.shell: |
        aws iam attach-role-policy \
          --role-name {{ lambda_role_name }} \
          --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      when: "'AWSLambdaBasicExecutionRole' not in attached_policies.stdout"
      args:
        executable: /bin/bash
        warn: false

    # ------------------------
    # Lambda Package
    # ------------------------
    - name: Package Lambda handler
      ansible.builtin.shell: |
        cd environments
        zip -r ../handler.zip handler.py
      args:
        executable: /bin/bash
        warn: false
      changed_when: true

    - name: Ensure Lambda function exists
      ansible.builtin.shell: |
        aws lambda get-function --function-name {{ lambda_name }} >/dev/null 2>&1
        if [ $? -ne 0 ]; then
          aws lambda create-function \
            --function-name {{ lambda_name }} \
            --runtime python3.11 \
            --role arn:aws:iam::{{ account_id }}:role/{{ lambda_role_name }} \
            --handler handler.lambda_handler \
            --zip-file fileb://handler.zip \
            --region {{ region }}
          echo "created"
        else
          echo "exists"
        fi
      args:
        executable: /bin/bash
        warn: false
      register: lambda_create_result
      changed_when: "'created' in lambda_create_result.stdout"

    - name: Get Lambda ARN
      ansible.builtin.shell: |
        aws lambda get-function \
          --function-name {{ lambda_name }} \
          --query 'Configuration.FunctionArn' \
          --output text \
          --region {{ region }}
      args:
        executable: /bin/bash
        warn: false
      register: lambda_arn_result
      changed_when: false

    - name: Set Lambda ARN fact
      ansible.builtin.set_fact:
        lambda_arn: "{{ lambda_arn_result.stdout }}"

    # ------------------------
    # SNS
    # ------------------------
    - name: Ensure SNS topic exists
      ansible.builtin.shell: |
        aws sns create-topic \
          --name {{ sns_topic_name }} \
          --region {{ region }}
      args:
        executable: /bin/bash
        warn: false
      register: sns_topic_result
      changed_when: "'TopicArn' in sns_topic_result.stdout"

    - name: Set SNS topic ARN fact
      ansible.builtin.set_fact:
        sns_topic_arn: "{{ (sns_topic_result.stdout | from_json).TopicArn }}"

    - name: Ensure SNS email subscriptions exist
      ansible.builtin.shell: |
        aws sns subscribe \
          --topic-arn {{ sns_topic_arn }} \
          --protocol email \
          --notification-endpoint {{ item }} \
          --region {{ region }}
      loop: "{{ email_subscriptions }}"
      args:
        executable: /bin/bash
        warn: false
      changed_when: true

    # ------------------------
    # S3 → Lambda Trigger
    # ------------------------
    - name: Ensure S3 permission exists for Lambda
      ansible.builtin.shell: |
        aws lambda get-policy --function-name {{ lambda_name }} >/dev/null 2>&1
        if [ $? -ne 0 ]; then
          aws lambda add-permission \
            --function-name {{ lambda_name }} \
            --statement-id s3invoke \
            --action lambda:InvokeFunction \
            --principal s3.amazonaws.com \
            --source-arn arn:aws:s3:::{{ s3_bucket_name }} \
            --region {{ region }}
          echo "added"
        else
          echo "exists"
        fi
      args:
        executable: /bin/bash
        warn: false
      register: lambda_permission_result
      changed_when: "'added' in lambda_permission_result.stdout"

    - name: Configure S3 notification for Lambda
      ansible.builtin.shell: |
        aws s3api put-bucket-notification-configuration \
          --bucket {{ s3_bucket_name }} \
          --notification-configuration '{
            "LambdaFunctionConfigurations":[{
              "LambdaFunctionArn":"{{ lambda_arn }}",
              "Events":["s3:ObjectCreated:Put"],
              "Filter":{"Key":{"FilterRules":[{"Name":"suffix","Value":".txt"}]}}
            }]
          }'
      args:
        executable: /bin/bash
        warn: false
      changed_when: false
